config/routes.rb
Rails.application.routes.draw do
  resources :galleries
  resources :conditions
  resources :vets
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
   resources :home
  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
 if user.admin?


 else 

 end

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    mount_uploader :images, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vet.rb
class Vet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: %i[ show edit update destroy ]

  # GET /conditions or /conditions.json
  def index
    @conditions = Condition.all
  end

  # GET /conditions/1 or /conditions/1.json
  def show
  end

  # GET /conditions/new
  def new
    @condition = Condition.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions or /conditions.json
  def create
    @condition = Condition.new(condition_params)

    respond_to do |format|
      if @condition.save
        format.html { redirect_to condition_url(@condition), notice: "Condition was successfully created." }
        format.json { render :show, status: :created, location: @condition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conditions/1 or /conditions/1.json
  def update
    respond_to do |format|
      if @condition.update(condition_params)
        format.html { redirect_to condition_url(@condition), notice: "Condition was successfully updated." }
        format.json { render :show, status: :ok, location: @condition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1 or /conditions/1.json
  def destroy
    @condition.destroy

    respond_to do |format|
      format.html { redirect_to conditions_url, notice: "Condition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def condition_params
      params.require(:condition).permit(:attendence, :durarion, :place, :datetime)
    end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i[ show edit update destroy ]

  # GET /galleries or /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1 or /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to gallery_url(@gallery), notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.require(:gallery).permit(:name, :description, :images)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
  def home
  
  end  
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  before_action :set_vet, only: %i[ show edit update destroy ]

  # GET /vets or /vets.json
  def index
    @vets = Vet.all
  end

  # GET /vets/1 or /vets/1.json
  def show
  end

  # GET /vets/new
  def new
    @vet = Vet.new
  end

  # GET /vets/1/edit
  def edit
  end

  # POST /vets or /vets.json
  def create
    @vet = Vet.new(vet_params)

    respond_to do |format|
      if @vet.save
        format.html { redirect_to vet_url(@vet), notice: "Vet was successfully created." }
        format.json { render :show, status: :created, location: @vet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vets/1 or /vets/1.json
  def update
    respond_to do |format|
      if @vet.update(vet_params)
        format.html { redirect_to vet_url(@vet), notice: "Vet was successfully updated." }
        format.json { render :show, status: :ok, location: @vet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vets/1 or /vets/1.json
  def destroy
    @vet.destroy

    respond_to do |format|
      format.html { redirect_to vets_url, notice: "Vet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vet
      @vet = Vet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vet_params
      params.require(:vet).permit(:Name, :crew, :birthday, :dog_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/conditions/_condition.html.erb
<div id="<%= dom_id condition %>">
  <p>
    <strong>Attendence:</strong>
    <%= condition.attendence %>
  </p>

  <p>
    <strong>Durarion:</strong>
    <%= condition.durarion %>
  </p>

  <p>
    <strong>Place:</strong>
    <%= condition.place %>
  </p>

  <p>
    <strong>Datetime:</strong>
    <%= condition.datetime %>
  </p>

</div>

app/views/conditions/_form.html.erb
<%= form_with(model: condition) do |form| %>
  <% if condition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(condition.errors.count, "error") %> prohibited this condition from being saved:</h2>

      <ul>
        <% condition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :attendence, style: "display: block" %>
    <%= form.number_field :attendence %>
  </div>

  <div>
    <%= form.label :durarion, style: "display: block" %>
    <%= form.number_field :durarion %>
  </div>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.label :datetime, style: "display: block" %>
    <%= form.date_field :datetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/conditions/edit.html.erb
<h1>Editing condition</h1>

<%= render "form", condition: @condition %>

<br>

<div>
  <%= link_to "Show this condition", @condition %> |
  <%= link_to "Back to conditions", conditions_path %>
</div>

app/views/conditions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Conditions</h1>

<div id="conditions">
  <% @conditions.each do |condition| %>
    <%= render condition %>
    <p>
      <%= link_to "Show this condition", condition %>
    </p>
  <% end %>
</div>

<%= link_to "New condition", new_condition_path %>

app/views/conditions/new.html.erb
<h1>New condition</h1>

<%= render "form", condition: @condition %>

<br>

<div>
  <%= link_to "Back to conditions", conditions_path %>
</div>

app/views/conditions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @condition %>

<div>
  <%= link_to "Edit this condition", edit_condition_path(@condition) %> |
  <%= link_to "Back to conditions", conditions_path %>

  <%= button_to "Destroy this condition", @condition, method: :delete %>
</div>

app/views/galleries/_form.html.erb
<%= form_with(model: gallery) do |form| %>
  <% if gallery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
        <% gallery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :images %>
    <%= form.file_field :images %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/galleries/_gallery.html.erb
<div id="<%= dom_id gallery %>">
  <p>
    <strong>Name:</strong>
    <%= gallery.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= gallery.description %>
  </p>

  <p>
    <strong>Images:</strong>
    <%= gallery.images %>
  </p>

</div>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Show this gallery", @gallery %> |
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Galleries</h1>

<div id="galleries">
  <% @galleries.each do |gallery| %>
    <%= render gallery %>
    <p>
      <%= link_to "Show this gallery", gallery %>
    </p>
  <% end %>
</div>

<%= link_to "New gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery esta es</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gallery %>

<div>
  <%= link_to "Edit this gallery", edit_gallery_path(@gallery) %> |
  <%= link_to "Back to galleries", galleries_path %>

  <%= button_to "Destroy this gallery", @gallery, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>esta es la pagina uno</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdoptaMascotashito3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </head>

  <body>
    <div class="container">


    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <div class="container-fluid">
      <a class="navbar-brand" href="img/logo.jpg">AdoptaMascotas</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/home" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Home
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/galleries">Galeria</a></li>
              <li><a class="dropdown-item" href="/contacto">Contacto</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Mascotas
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/vets">Listar</a></li>
              <li><a class="dropdown-item" href="/vets/new">Nuevo</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Condiciones
            </a>            
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/conditions">Listar</a></li>
              <li><a class="dropdown-item" href="/conditions/new">Nuevo</a></li>
            </ul>            
          </li>
 
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/ingresar" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Logearse
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="/mascotas">Log-in</a></li>
              <li><a class="dropdown-item" href="/users/sign_in"><%= link_to 'Log-out', destroy_user_session_path, method: :delete %></a></li>
            </ul>
          </li>
        </ul>

      </div>
    </div>
    </nav>



    

     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     
     <% if current_user %>
    <%= current_user.email %>
    <%= button_to 'Log out' , destroy_user_session_path, method: :delete,data: { turbo: false }%>
      
     <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/vets/_form.html.erb
<%= form_with(model: vet) do |form| %>
  <% if vet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vet.errors.count, "error") %> prohibited this vet from being saved:</h2>

      <ul>
        <% vet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3 row form-control-lg">
    <label class="col-sm-2 col-form-label">Nombre </label>
    <div class="col-sm-10">
    <%= form.text_field :Name %>
  </div>
  </div>

  <div class="mb-3 row form-control-lg">
    <label class="col-sm-2 col-form-label">Dimension </label>
    <div class="col-sm-10">
    <%= form.number_field :crew %>
  </div>
  </div>

  <div class="mb-3 row form-control-lg">
    <label class="col-sm-2 col-form-label">Fecha nacimiento </label>
    <div class="col-sm-10">
    <%= form.date_field :birthday %>
  </div>
  </div>

  <div class="mb-3 row form-control-lg">
    <label class="col-sm-2 col-form-label">tipo perro </label>
    <div class="col-sm-10">
    <%= form.number_field :dog_type %>
  </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vets/_vet.html.erb
<div id="<%= dom_id vet %>">
  <p>
    <strong>Name:</strong>
    <%= vet.Name %>
  </p>

  <p>
    <strong>Crew:</strong>
    <%= vet.crew %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= vet.birthday %>
  </p>

  <p>
    <strong>Dog type:</strong>
    <%= vet.dog_type %>
  </p>

</div>

app/views/vets/edit.html.erb
<h1>Editing vet</h1>

<%= render "form", vet: @vet %>

<br>

<div>
  <%= link_to "Show this vet", @vet %> |
  <%= link_to "Back to vets", vets_path %>
</div>

app/views/vets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vets</h1>

<div id="vets">
  <% @vets.each do |vet| %>
    <%= render vet %>
    <p>
      <%= link_to "Show this vet", vet %>
    </p>
  <% end %>
</div>

<%= link_to "New vet", new_vet_path %>

app/views/vets/new.html.erb
<h1>New vet</h1>

<%= render "form", vet: @vet %>

<br>

<div>
  <%= link_to "Back to vets", vets_path %>
</div>

app/views/vets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vet %>

<div>
  <%= link_to "Edit this vet", edit_vet_path(@vet) %> |
  <%= link_to "Back to vets", vets_path %>

  <%= button_to "Destroy this vet", @vet, method: :delete %>
</div>